package formulario;

import servidor.RMIServidor;

public class FrmServidor extends javax.swing.JFrame {

    /**
     * Creates new form FrmServidor
     */
    public FrmServidor() {
        initComponents();
        jBtIniciar.setEnabled(true);
        jBtParar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jBtIniciar = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTALog = new javax.swing.JTextArea();
        jLabelLog = new javax.swing.JLabel();
        jPHostSocket = new javax.swing.JPanel();
        jLPortaSocket = new javax.swing.JLabel();
        jTfPortaSocket = new javax.swing.JTextField();
        jTfEnderecoCoordenador = new javax.swing.JTextField();
        jLabelEnderecoCoordenador = new javax.swing.JLabel();
        jPainelServidor = new javax.swing.JPanel();
        jTfNomeServidorRMI = new javax.swing.JTextField();
        jLabelNomeServidor = new javax.swing.JLabel();
        jLPortaRMI = new javax.swing.JLabel();
        jTfPortaRMI = new javax.swing.JTextField();
        jBtParar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor Replicado");

        jBtIniciar.setText("Iniciar");
        jBtIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtIniciarActionPerformed(evt);
            }
        });

        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        jTALog.setColumns(20);
        jTALog.setRows(5);
        jScrollPane1.setViewportView(jTALog);

        jLabelLog.setText("Log");

        jPHostSocket.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLPortaSocket.setText("Porta Socket:");

        jTfPortaSocket.setText("4444");
        jTfPortaSocket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfPortaSocketActionPerformed(evt);
            }
        });

        jTfEnderecoCoordenador.setText("localhost");

        jLabelEnderecoCoordenador.setText("Endereço Coordenador:");

        javax.swing.GroupLayout jPHostSocketLayout = new javax.swing.GroupLayout(jPHostSocket);
        jPHostSocket.setLayout(jPHostSocketLayout);
        jPHostSocketLayout.setHorizontalGroup(
            jPHostSocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHostSocketLayout.createSequentialGroup()
                .addGroup(jPHostSocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEnderecoCoordenador, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jTfEnderecoCoordenador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPHostSocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTfPortaSocket, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPortaSocket, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPHostSocketLayout.setVerticalGroup(
            jPHostSocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPHostSocketLayout.createSequentialGroup()
                .addGroup(jPHostSocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPortaSocket)
                    .addComponent(jLabelEnderecoCoordenador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPHostSocketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfEnderecoCoordenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfPortaSocket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPainelServidor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTfNomeServidorRMI.setText("Servidor");

        jLabelNomeServidor.setText("Nome Servidor:");

        jLPortaRMI.setText("Porta RMI:");

        jTfPortaRMI.setText("1099");

        javax.swing.GroupLayout jPainelServidorLayout = new javax.swing.GroupLayout(jPainelServidor);
        jPainelServidor.setLayout(jPainelServidorLayout);
        jPainelServidorLayout.setHorizontalGroup(
            jPainelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelServidorLayout.createSequentialGroup()
                .addGroup(jPainelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNomeServidor, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jTfNomeServidorRMI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPainelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTfPortaRMI, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPortaRMI, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPainelServidorLayout.setVerticalGroup(
            jPainelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPainelServidorLayout.createSequentialGroup()
                .addGroup(jPainelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeServidor)
                    .addComponent(jLPortaRMI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPainelServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfNomeServidorRMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfPortaRMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtParar.setText("Parar");
        jBtParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPHostSocket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPainelServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelLog))
                .addGap(18, 212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jBtParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPainelServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtParar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPHostSocket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelLog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBFechar)
                        .addGap(16, 16, 16)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtIniciarActionPerformed
        // TODO add your handling code here:
        //Limpa a caixa de log
        jTALog.setText("");
        //Recupera os dados da interface
        String nomeServidor = jTfNomeServidorRMI.getText();
        String enderecoCoordenador = jTfEnderecoCoordenador.getText();
        int porta = Integer.parseInt(jTfPortaRMI.getText());
        int portaSocket = Integer.parseInt(jTfPortaSocket.getText());
        //Instancia o servidor RMI
        servidorRMI = new RMIServidor(nomeServidor, enderecoCoordenador, porta, portaSocket, jTALog);

        try {
            Runnable simple = new Runnable() {
                public void run() {
                    servidorRMI.executar();
                }
            };
            new Thread(simple).start();
        } catch (Exception x) {
            x.printStackTrace();
        }
        //Habilita os botões
        jBtIniciar.setEnabled(false);
        jBtParar.setEnabled(true);

    }//GEN-LAST:event_jBtIniciarActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jTfPortaSocketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfPortaSocketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfPortaSocketActionPerformed

    private void jBtPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPararActionPerformed
        // TODO add your handling code here:s
        jBtIniciar.setEnabled(true);
        servidorRMI.parar();
        jBtParar.setEnabled(false);
    }//GEN-LAST:event_jBtPararActionPerformed

    private RMIServidor servidorRMI;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBtIniciar;
    private javax.swing.JButton jBtParar;
    private javax.swing.JLabel jLPortaRMI;
    private javax.swing.JLabel jLPortaSocket;
    private javax.swing.JLabel jLabelEnderecoCoordenador;
    private javax.swing.JLabel jLabelLog;
    private javax.swing.JLabel jLabelNomeServidor;
    private javax.swing.JPanel jPHostSocket;
    private javax.swing.JPanel jPainelServidor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTALog;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTfEnderecoCoordenador;
    private javax.swing.JTextField jTfNomeServidorRMI;
    private javax.swing.JTextField jTfPortaRMI;
    private javax.swing.JTextField jTfPortaSocket;
    // End of variables declaration//GEN-END:variables
}
